---
# This playbook deploys the whole demo enviroment.

- name: Build hosts inventory in memory for localhost
  hosts: localhost
  gather_facts: no
  vars_files:
  - group_vars/mds_var.yml
  - group_vars/sm_var.yml
  - group_vars/smsg_var.yml
  - group_vars/sg_var.yml
  roles:
    - role: inventory
      tags: [ "always" ]

- name: Deploy a virtual machine as Security Management Server server
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sm_var.yml
  roles:
    - role: vmrun
      tags: [ "prepp-demo" ]

- name: Configure Gaia OS on Security Management Server server
  hosts: 
  - "{{ target }}"
  - "{{ groups['gaia_template'][0] }}"
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sm_var.yml
  roles:
    - role: gaia
      tags: [ "prepp-demo" ]

- name: Configure Security Management Server Server using The R80.x Security Management API
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sm_var.yml
  - fingerprints/sm_finger.yml
  roles:
    - role: r80api
      mgmt_fingerprint: "{{ hostvars[groups['sm'][0]]['mgmt_fingerprint'] }}"
    - role: r80api
      tags: [ "never", "sg-demo" ]
#      mgmt_fingerprint: "{{ hostvars[groups['sm'][0]]['mgmt_fingerprint'] }}"

# Deploy a Security Gateway and configure it in the nordics domain
- name: Deploy a virtual machine as SG server
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sg_var.yml
  roles:
  - role: vmrun
    tags: [ "sg-demo" ]
    hostname: sm-sg253

- name: Configure Gaia OS on SG server
  hosts: 
  - "{{ target }}"
  - "{{ groups['gaia_template'][0] }}"
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sg_var.yml
  roles:
  - role: gaia
    tags: [ "sg-demo" ]
    hostname: sm-sg253

- name: Configure SG Server using The R80.x Security Management API
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
  - group_vars/sg_var.yml
  - fingerprints/sm_finger.yml
  roles:
  - role: r80api
    hostname: sm-sg253
    mgmt_server: "{{ groups['sm'][0] }}"
    mgmt_fingerprint: "{{ hostvars[groups['sm'][0]]['mgmt_fingerprint'] }}"
    domain: SMC User
  - role: r80api
    tags: [ "never", "sg-demo" ]
    hostname: sm-sg253
    mgmt_server: "{{ groups['sm'][0] }}"
#    mgmt_fingerprint: "{{ hostvars[groups['sm'][0]]['mgmt_fingerprint'] }}"
    domain: SMC User

- name: Deploy our E-comerce web server
  hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - role: vmrun
    tags: [ "never", "sg-demo", "webserver" ]
    hostname: WebServer
    type: webserver